### ISSUE TITLE
API List

### ISSUE THREAD

**Issue by majorazero** [majorazero/project-1#2]
Post the relevant API's we need and their links and doc.

**Comment by AndyTamez** [comment]
https://developers.google.com/maps/documentation/urls/guide

**Comment by davidmhuh** [comment]
https://developer.yahoo.com/weather/#get-started ~ yahoo weather
https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Boston%20%2CMA%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys - endpoint for yahoo weather

**Comment by majorazero** [comment]
Unnecessary issue now.
