### ISSUE TITLE
API Calls - Flight

### ISSUE THREAD

**Issue by majorazero** [majorazero/project-1#3]
**Please test whatever flight API we decide to use and make sure it can get at least the following information...**

- Airline/s
- Departure/Arrival from point A to point B
- Price

**Additional things to consider:**

- Layovers? 
- Is the data sortable? (Will it just give us a lot of flights, how do the query system work)
- Limitations of the API calls (if its better to call it once, or is it easy for us to call it whenever we need to... I guess the limit of its abuse?) 
- Anything else you can think of that could potentially be useful things we can get from the data. 

**Close the issue after you post a link to the documentation, the API key and the API calls we'll probably be using too. (Especially if the documentation is BAD.)**

**Comment by davidmhuh** [comment]
Saber  Dev Studios -
Flights API
Key: V1:17rw2ul9hv3npb4l:DEVCENTER:EXT
Application:
david huh's App
Key:
V1:17rw2ul9hv3npb4l:DEVCENTER:EXT
Shared Secret:
jO0GY8ms
