### ISSUE TITLE
API Calls - Hotels

### ISSUE THREAD

**Issue by majorazero** [majorazero/project-1#4]
**Please test whatever flight API we decide to use and make sure it can get at least the following information...**
- Location
- Price for length of stay
- Rating

**Additional things to consider:**

- Are there deals to consider? (Can the API tell us that?)
- Is the data sortable? (Will it just give us a lot of hotels, how do the query system work)
- Limitations of the API calls (if its better to call it once, or is it easy for us to call it whenever we need to... I guess the limit of its abuse?)
- Anything else you can think of that could potentially be useful things we can get from the data.

**Close the issue after you post a link to the documentation, the API key and the API calls we'll probably be using too. (Especially if the documentation is BAD.)**

**Comment by davidmhuh** [comment]
closed
