### ISSUE TITLE
API Calls - Restaurants/ Sights

### ISSUE THREAD

**Issue by majorazero** [majorazero/project-1#5]
**Please test whatever restaurant/landmarks (probably Yelp, Zomato or Tripadvisor somehow) API we decide to use and make sure it can get at least the following information...**

- Location
- Name of Restaurant / Sights
- Type of Food (If restaurant)
- Price Range (Yelp has $$$$, not sure what the other has)
- Rating

**Additional things to consider:**

- Would be nice if there was a pic we can grab too.
- Are there top highlights or tips about the location? Maybe top menu item.
- Is the data sortable? (Will it just give us a lot of resturants, how do the query system work)
- Limitations of the API calls (if its better to call it once, or is it easy for us to call it whenever we need to... I guess the limit of its abuse?)
- Anything else you can think of that could potentially be useful things we can get from the data.

**Close the issue after you post a link to the documentation, the API key and the API calls we'll probably be using too. (Especially if the documentation is BAD.)**

**Comment by davidmhuh** [comment]
API key: SUF59kahcN2IXJfeCVDDS7peYrVI9ioF2YPAwKjO
Documentation: http://docs.sygictravelapi.com/ or https://travel.sygic.com/b2b/documentation for SDKs. (SDKs are native code libraries for Android, iOS and JavaScript that handle common Sygic Travel API use cases, such as spreading and displaying point of interest markers over a map, and enable working with use data, such as saving favorite places or creating trip itinerary for a user.) 
Limits for the test key: 40 requests/second (average), 200 requests is max burst.

For example, you can use the following query to get the list of top 100 POIs in New York City:
https://api.sygictravelapi.com/1.0/en/places/list?parents=city:186&level=poi&limit=100
Note that the URL does not work in the browser, you need to send a "x-api-key" header along with the HTTP request. We recommend using an API tool (e.g. Postman) to explore the API.

For each POI there is also a /place-details/ API endpoint, which will return all information for that POI including all contacts, opening hours, full description etc. See
https://api.sygictravelapi.com/1.0/en/places/poi:11875 for Chrysler Building.

**Comment by majorazero** [comment]
**API Key:** g9EeN1YvpMFGmbPjwKqrAVIVoCCCCK0g-uyPyF9nJigZOIKQpJYJa2S3FOUhlJ9Y6cnJszqMSRFjwrobfelVeALnWAHR1uBlC2L9fVkWZh0-sfqrvRZYjecDMWGRW3Yx
**Documentation:** https://www.yelp.com/developers/documentation/v3
Limit for key: 5000 for the month
**Display Requirements:** https://www.yelp.com/developers/display_requirements
Yelp requires us to tell the user our app is powered by yelp. Our application is for our projects only, but it could be an interesting learning experience to implement some of their requirement. 
**Data Details**
Here's an example of what the data looks like.
```````
{
  "total": 8228,
  "businesses": [
    {
      "rating": 4,
      "price": "$",
      "phone": "+14152520800",
      "id": "E8RJkjfdcwgtyoPMjQ_Olg",
      "alias": "four-barrel-coffee-san-francisco",
      "is_closed": false,
      "categories": [
        {
          "alias": "coffee",
          "title": "Coffee & Tea"
        }
      ],
      "review_count": 1738,
      "name": "Four Barrel Coffee",
      "url": "https://www.yelp.com/biz/four-barrel-coffee-san-francisco",
      "coordinates": {
        "latitude": 37.7670169511878,
        "longitude": -122.42184275
      },
      "image_url": "http://s3-media2.fl.yelpcdn.com/bphoto/MmgtASP3l_t4tPCL1iAsCg/o.jpg",
      "location": {
        "city": "San Francisco",
        "country": "US",
        "address2": "",
        "address3": "",
        "state": "CA",
        "address1": "375 Valencia St",
        "zip_code": "94103"
      },
      "distance": 1604.23,
      "transactions": ["pickup", "delivery"]
    },
    // ...
  ],
  "region": {
    "center": {
      "latitude": 37.767413217936834,
      "longitude": -122.42820739746094
    }
  }
}
```````
For our geo-tracker apps or routing apps we'll prob need to pull the latitude and longitude instead of an "address" since addresses language and format may vary between countries.
