### ISSUE TITLE
HTML - Basic Bootstrap Implementation

### ISSUE THREAD

**Issue by majorazero** [majorazero/project-1#7]
The HTML body needs to have all the Bootstrap container, rows, and columns etc. set up. I think ideally we make this a single page application, so please design it with features fading in and fading out, appending and prepending etc. in mind. 

Really thinking of like each page as its own unique row basically. 

Also don't forget to comment in what each row or column should be for clarity. 
i.e. 
``````
 <!-- This is the front page -->
  <div class = "row">
    <div class = "col-md-12"></div>
  </div>
``````

**Comment by AndyTamez** [comment]
finished it
