### ISSUE TITLE
Javascript - Hotel Query

### ISSUE THREAD

**Issue by majorazero** [majorazero/project-1#9]
**Write a function that will return an array of objects that has the information we'd want about the hotels (refer to API requirements). Given the parameters...**

1. Duration, (... or start date, end date)
2. Location (Probably a city.)

**We want at least 3 hotel details returned, though hopefully the results we want should be variable. (If we need 7 later, that should not be an issue.), and if there are bonus info you think we would want, make sure the function can handle it.**

**Make sure the object you organize the information into is easy for everyone to understand.**

**Comment by davidmhuh** [comment]
closed
